import type { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { registerSendDm } from "./send-dm.js";
import { registerBroadcast } from "./broadcast.js";
import { registerCreateScenario } from "./create-scenario.js";
import { registerEnrollScenario } from "./enroll-scenario.js";
import { registerManageTags } from "./manage-tags.js";
import { registerCreateForm } from "./create-form.js";
import { registerCreateTrackedLink } from "./create-tracked-link.js";
import { registerCreateCommentRule } from "./create-comment-rule.js";
import { registerListFollowers } from "./list-followers.js";
import { registerGetFollowerDetail } from "./get-follower-detail.js";
import { registerGetFormSubmissions } from "./get-form-submissions.js";
import { registerGetLinkClicks } from "./get-link-clicks.js";
import { registerAccountSummary } from "./account-summary.js";
import { registerListCrmObjects } from "./list-crm-objects.js";
import { registerManageStaff } from "./manage-staff.js";
import { registerUploadImage } from "./upload-image.js";
import { registerManageFollowers } from "./manage-followers.js";
import { registerManageScenarios } from "./manage-scenarios.js";
import { registerManageBroadcasts } from "./manage-broadcasts.js";
import { registerManageCommentRules } from "./manage-comment-rules.js";
import { registerManageForms } from "./manage-forms.js";
import { registerManageTrackedLinks } from "./manage-tracked-links.js";
import { registerManageEngagementGates } from "./manage-engagement-gates.js";
import { registerManageLineConnections } from "./manage-line-connections.js";
import { registerManageRichMessages } from "./manage-rich-messages.js";
import { registerListRecentReels } from "./list-recent-reels.js";
import { registerBulkApplyGatesToReels } from "./bulk-apply-gates.js";

export function registerAllTools(server: McpServer): void {
  registerSendDm(server);
  registerBroadcast(server);
  registerCreateScenario(server);
  registerEnrollScenario(server);
  registerManageTags(server);
  registerCreateForm(server);
  registerCreateTrackedLink(server);
  registerCreateCommentRule(server);
  registerListFollowers(server);
  registerGetFollowerDetail(server);
  registerGetFormSubmissions(server);
  registerGetLinkClicks(server);
  registerAccountSummary(server);
  registerListCrmObjects(server);
  registerManageStaff(server);
  registerUploadImage(server);
  registerManageFollowers(server);
  registerManageScenarios(server);
  registerManageBroadcasts(server);
  registerManageCommentRules(server);
  registerManageForms(server);
  registerManageTrackedLinks(server);
  registerManageEngagementGates(server);
  registerManageLineConnections(server);
  registerManageRichMessages(server);
  registerListRecentReels(server);
  registerBulkApplyGatesToReels(server);
}
